name: Deploy to Server

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/scp-action@0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ vars.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: "."
          target: "/home/frappe/frappe-bench/apps/zamtel_payments"